name: Deploy TaskManager WebUi (Docker)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Build imagem Docker da WebUi
        run: docker build -f TaskManager.WebUi/Dockerfile -t taskmanager-webui .

      - name: Deploy para Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: taskmanager-webui
          publish-profile: ${{ secrets.AZURE_WEBUI_PUBLISH_PROFILE }}
          images: taskmanager-webui
