name: Deploy TaskManager WebUi (Código)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Publicar projeto WebUi
        run: dotnet publish TaskManager.WebUi/TaskManager.WebUi.csproj -c Release -o ./publish

      - name: Deploy para Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: taskmanager-web-ui
          package: ./publish
