name: Deploy TaskManager API (Docker)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build da imagem Docker da API
        run: docker build -f TaskManager.API/Dockerfile -t taskmanager-api .

      - name: Deploy para Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: taskmanager-api
          images: taskmanager-api
